### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [millanzarreta/LoseControl#2]
Installing LoseControl for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/170845723-d22115ff-a3bc-4d3c-a464-abd2066343f9.png)

The URL used for installing for the above image was: https://github.com/millanzarreta/LoseControl

In order for WoWUp to recognize this repository, you must create a [Release](https://github.com/millanzarreta/LoseControl/releases) that includes a `.zip` file whose file name ends with `-bcc`. For example the zip file may be called `LoseControl.v1.0.0-bcc.zip`

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by millanzarreta** [comment]
Hello. Thanks for the suggestion, but, sorry. Serving this repository as an addon source for addon managers is not currently in my plans and I doubt it will be in the future. It already takes quite a long time to handle the updates of all my addons on the different sites like CurseForge, WoWInterface (and the code in Github), and there are more and more new alternatives (WowUp Hub, Wago, etc...).

I know a lot of people don't like Overwolf, but you don't need to use their main app to download CurseForge addons as they have released a separate addon client for this purpose.

Even so. If you don't like CurseForge/Overwolf (or anything related to them), the addon is available on WoWInterface, and WoWUp should be able to use this site as a source for this addon. I think WoWInterface is a trusted addon provider that fills the need for those who dislike CurseForge/Overwolf and prefer to use WoWUp (or some other free addon manager).
